name: Creating CI pipeline

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run selenium code
    runs-on: ubuntu-latest
    steps:
      - name: Set up python version
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
              architecture: 'x64'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Setup and run tests
        working-directory: selenium-codes/
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Give execution permission to trigger
        run: chmod +x execute.sh
      - name: Execute trigger
        run: ./execute.sh --regression
        env:
          DEFAULT_BRANCH: master